---
title: "检查数据质量"
output: html_notebook
---

本脚本用于检查双维度PC实验中的比例是否正确

## 1. 导入数据并修改其中的Code
```{r}
library(tidyverse)
test_data <- readLines("pre_from_master/1-LearnPC_Space7525_Color7525.log")

# Changing the code
test_data <- test_data %>% 
    str_replace("SpaceCon-ColorCon-Red", "SpaceCon-ColorCon") %>% 
    str_replace("SpaceCon-ColorInc-Red", "SpaceCon-ColorInC") %>% 
    str_replace("SpaceInc-ColorCon-Red", "SpaceInC-ColorCon") %>% 
    str_replace("SpaceInC-ColorInC-Red", "SpaceInC-ColorInC") %>% 
    str_replace("SpaceCon-ColorCon-Circle", "SpaceCon-ColorCon") %>% 
    str_replace("SpaceCon-ColorInC-Circle", "SpaceCon-ColorInC") %>% 
    str_replace("SpaceInC-ColorCon-Circle", "SpaceInC-ColorCon") %>% 
    str_replace("SpaceInC-ColorInC-Circle", "SpaceInC-ColorInC") %>% 
    str_replace("SpaceCon-ColorCon-Green", "SpaceCon-ColorCon") %>% 
    str_replace("SpaceCon-ColorInC-Green", "SpaceCon-ColorInC") %>% 
    str_replace("SpaceCon-ColorInC_Green", "SpaceCon-ColorInC") %>% 
    str_replace("SpaceInC-ColorCon_Green", "SpaceInC-ColorCon") %>% 
    str_replace("SpaceInC-ColorCon-Green", "SpaceInC-ColorCon") %>% 
    str_replace("SpaceInC-ColorInC-Green", "SpaceInC-ColorInC") %>% 
    str_replace("SpaceCon-ColorCon-Circle-Green", "SpaceCon-ColorCon") %>% 
    str_replace("SpaceCon-ColorInC-Circle_Green", "SpaceCon-ColorInC") %>% 
    str_replace("SpaceInC-ColorCon-Circle_Green", "SpaceInC-ColorCon") %>%
    str_replace("SpaceInc-ColorCon", "SpaceInC-ColorCon") %>%
    str_replace("SpaceInC-ColorInC-Circle-Green", "SpaceInC-ColorInC") 

RT_index <- which(stringr::str_detect(test_data,"RT"))[[1]]
RT_end <- which(str_detect(test_data,"end_message"))[[2]]

c(test_data[RT_index], test_data[(RT_index + 2) : RT_end]) %>% 
  textConnection() %>% 
  read.table(sep = "\t", header = T) -> RT_table

RT_table <- RT_table %>% 
  filter(grepl('Space', Code))

Exercise_table <- RT_table[1:32,]
Block1 <- RT_table[33:672,]
Block2 <- RT_table[673:1312,]
```

## 2. 计算不同条件下的比例
### 在Block1中
Color条件下Con：InC为
```{r}
sum(str_detect(Block1$Code,"ColorCon"))/sum(str_detect(Block1$Code,"ColorInC")) %>% 
  MASS::fractions()
```
Space条件下Con：InC为
```{r}
sum(str_detect(Block1$Code,"SpaceCon"))/sum(str_detect(Block1$Code,"SpaceInC")) %>% 
  MASS::fractions()
```

### 在Block2中
Color条件下Con：InC为
```{r}
sum(str_detect(Block2$Code,"ColorCon"))/sum(str_detect(Block2$Code,"ColorInC")) %>% 
  MASS::fractions()
```
Space条件下Con：InC为
```{r}
sum(str_detect(Block2$Code,"SpaceCon"))/sum(str_detect(Block2$Code,"SpaceInC")) %>% 
  MASS::fractions()
```